language: java
<<<<<<< HEAD
cache:
  directories:
    - $HOME/.gradle
    - .gradle
sudo: false
before_install:
  - git submodule update --init --recursive
  - chmod a+x gradlew
=======
before_install:
  - git submodule update --init --recursive
>>>>>>> 38375e4795ef409df2e1bbea87372cb3be061c5e
notifications:
 irc:
  channels:
   - "irc.esper.net#BBM-bots"
  template:
   - "%{build_number} (%{branch} - %{commit}: %{commit_message} : %{author}): %{message} (%{build_url})"
install: true
script:
<<<<<<< HEAD
  - ./gradlew build -PbambooshortPlanName=VoltzEngine -Pdmodcurse=61545 --refresh-dependencies
=======
  - gradle build -PbambooshortPlanName=BBM-Dev -Pdmodcurse=61545 --refresh-dependencies
cache:
  directories:
    - $HOME/.gradle
    - .gradle
sudo: false
>>>>>>> 38375e4795ef409df2e1bbea87372cb3be061c5e
jdk:
  - oraclejdk7
  - openjdk6
