package madscience.metaitems;

import madscience.MadComponents;

public class MainframeComponentsMetadata
{
    public static final String[] getInternalNameFromDamage =
    { MadComponents.COMPONENT_CASE_INTERNALNAME, MadComponents.COMPONENT_CPU_INTERNALNAME, MadComponents.COMPONENT_FAN_INTERNALNAME, MadComponents.COMPONENT_POWERSUPPLY_INTERNALNAME, MadComponents.COMPONENT_RAM_INTERNALNAME,
            MadComponents.COMPONENT_SILICONWAFER_INTERNALNAME, MadComponents.COMPONENT_COMPUTER_INTERNALNAME, MadComponents.COMPONENT_SCREEN_INTERNALNAME, MadComponents.COMPONENT_TRANSISTOR_INTERNALNAME, MadComponents.COMPONENT_FUSEDQUARTZ_INTERNALNAME,
            MadComponents.COMPONENT_MAGNETICTAPE_INTERNALNAME, MadComponents.CIRCUIT_COMPARATOR_INTERNALNAME, MadComponents.CIRCUIT_DIAMOND_INTERNALNAME, MadComponents.CIRCUIT_EMERALD_INTERNALNAME, MadComponents.CIRCUIT_ENDEREYE_INTERNALNAME,
            MadComponents.CIRCUIT_ENDERPEARL_INTERNALNAME, MadComponents.CIRCUIT_GLOWSTONE_INTERNALNAME, MadComponents.CIRCUIT_REDSTONE_INTERNALNAME, MadComponents.CIRCUIT_SPIDEREYE_INTERNALNAME, };
}
